version: "3.9"

services:
  webapp:
    container_name: webapp
    build:
      context: webapp
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80"
    networks:
      - frontend
  applayer:
    container_name: applayer
    build:
      context: applayer
      dockerfile: Dockerfile
    environment:
      DB_USER: 'root'
      DB_PASSWORD: 'my-secret-pwd'
      DB_HOST: 'db'
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - backend
  db:
    container_name: db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'my-secret-pwd'
    restart: always
    ports:
      - "3306:3306"
    networks:
      - backend

networks:
  backend:
  frontend:
